# Generated by Django 4.1.7 on 2023-06-25 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_city_profile_gender_profile_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='otp',
        ),
    ]
