# Generated by Django 4.1.1 on 2022-09-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(height_field='50', upload_to='product_images', width_field='100'),
        ),
    ]
