# Generated by Django 4.1.1 on 2022-09-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_price_product_price_for_min_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_quantity',
            new_name='min_quantity_to_fix_price',
        ),
    ]
