# Generated by Django 4.1.1 on 2022-09-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_min_quantity_product_min_quantity_to_fix_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('packet', 'Packet')], default='kg', max_length=100),
        ),
    ]
