# Generated by Django 4.1.1 on 2022-09-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_product_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_quantity_to_fix_price',
            field=models.IntegerField(),
        ),
    ]
