# Generated by Django 4.1.1 on 2022-09-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_product_available_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
