# Generated by Django 4.1.7 on 2023-03-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('gm', 'Gram'), ('units', 'units'), ('litre', 'Litre'), ('units', 'units')], default='kg', max_length=100),
        ),
    ]
